In [1]:
#Shishir Khanal
#Jun 28, 2025
#Numpy intro
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [7]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [10]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [12]:
arr.shape

(3, 3)

In [14]:
#Not include 10
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
#similar to colon operator in matlab
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.0)

float

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
[1,1,1,1]*100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [23]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5,5)

array([[0.32968271, 0.66536596, 0.56080044, 0.77715787, 0.7300121 ],
       [0.26023775, 0.00879279, 0.20620064, 0.33688223, 0.34502821],
       [0.23663663, 0.4917508 , 0.83368562, 0.31531416, 0.62302646],
       [0.79483674, 0.56203124, 0.31867516, 0.25435439, 0.98837962],
       [0.4588896 , 0.89549007, 0.11504332, 0.39485437, 0.32039104]])

In [31]:
np.random.randn(10)

array([ 0.15629278, -0.61402179,  0.20423412, -0.50224149,  0.58571779,
       -0.99218921, -0.6020768 ,  0.81407424, -1.00369971,  1.82565223])

In [33]:
np.random.randint(1,100, 10)

array([91, 53,  2, 19, 79, 10, 16, 83, 82, 77])

In [39]:
#Seed and randon number generator should be in the same line
#this creates the same random number across different machines
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr.max()

39

In [49]:
ranarr.min()

2

In [51]:
ranarr.argmax()

7

In [52]:
ranarr.argmin()

9

In [53]:
#########################
#Indexing and Selection
#########################

In [82]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[1:5]

array([1, 2, 3, 4])

In [84]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [87]:
slice_of_arr_copy = arr_copy[0:6]
slice_of_arr_copy

array([0, 1, 2, 3, 4, 5])

In [88]:
slice_of_arr_copy[:] = 99

In [89]:
#broadcasting
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [92]:
#Indexing on 2D array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d.shape

(3, 3)

In [95]:
arr_2d[1][1]

25

In [96]:
arr_2d[2][2]

45

In [97]:
arr_2d[2,2]

45

In [99]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [102]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [104]:
#Return the elements which bool_arr at that index is true
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [105]:
#########################
#Operations
#########################

In [106]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [107]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [108]:
arr[1] = 0
arr

array([ 1,  0,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
1/arr

/home/shishir/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1.        ,        inf, 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [110]:
arr/arr

/home/shishir/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1., nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
np.log(arr)

/home/shishir/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([0.        ,       -inf, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [112]:
np.sin(arr)

array([ 0.84147098,  0.        ,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [114]:
arr.sum()

53

In [116]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
#Sum across the rows
# i.e. sum of each column
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [119]:
#sum of each row
arr_2d.sum(axis=1)

array([10, 26, 42])